# Generated by Django 5.0.6 on 2024-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmend', '0002_scores_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scores',
            name='selected_emotion',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
        migrations.AddField(
            model_name='scores',
            name='selected_emotions',
            field=models.ManyToManyField(related_name='scores', to='mindmend.emotion'),
        ),
    ]
