# Generated by Django 5.0.6 on 2024-07-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindmend', '0004_alter_subscription_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='desensitisation_emotions_after_therapy',
            new_name='After_therapy',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='desensitisation_emotions_before_therapy',
            new_name='Before_therapy',
        ),
    ]
