# Generated by Django 5.0.6 on 2024-07-02 10:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmend', '0005_rename_desensitisation_emotions_after_therapy_scores_after_therapy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='After_therapy',
            new_name='after_therapy',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='Before_therapy',
            new_name='before_therapy',
        ),
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scores',
            name='selected_emotions',
            field=models.ManyToManyField(related_name='current_scores', to='mindmend.emotion'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_therapy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('after_therapy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('general_emotion', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_emotions', models.ManyToManyField(related_name='score_records', to='mindmend.emotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
