# Generated by Django 5.0.6 on 2024-07-03 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmend', '0007_customuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ScoreRecord',
        ),
    ]
