# Generated by Django 5.0.6 on 2024-07-03 16:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmend', '0008_alter_scores_user_delete_scorerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_therapy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('after_therapy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('general_emotion', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_emotions', models.ManyToManyField(related_name='score_records', to='mindmend.emotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
